// <auto-generated />
using System;
using ControlEscolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlEscolar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlEscolar.Models.ArchivoDescargaViewModel", b =>
                {
                    b.Property<string>("ArchivoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivoFisico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRequisito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchivoDescargaViewModel");
                });

            modelBuilder.Entity("ControlEscolar.Models.Cat_Tramites", b =>
                {
                    b.Property<int>("id_tramite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tramite"));

                    b.Property<string>("nombre_tramite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tramite");

                    b.ToTable("CE_TramitesCategoria", "dbo");
                });

            modelBuilder.Entity("ControlEscolar.Models.ConfiguracionFichasEntity", b =>
                {
                    b.Property<int>("academiccontrol_inscription_ticketconfig_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_inscription_ticketconfig_ID"));

                    b.Property<string>("academiccontrol_inscription_ticketconfig_career")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_career");

                    b.Property<DateTime>("academiccontrol_inscription_ticketconfig_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("academiccontrol_inscription_ticketconfig_endDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_endDate");

                    b.Property<int>("academiccontrol_inscription_ticketconfig_limit")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_limit");

                    b.Property<DateTime>("academiccontrol_inscription_ticketconfig_startDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_startDate");

                    b.Property<bool>("academiccontrol_inscription_ticketconfig_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_inscription_ticketconfig_status");

                    b.Property<DateTime>("academiccontrol_inscription_ticketconfig_updatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_ticketconfig_updatedDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("academiccontrol_inscription_ticketconfig_ID");

                    b.ToTable("academiccontrol_inscription_ticketconfig_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.DetalleDocumentos", b =>
                {
                    b.Property<int>("id_detalle_doc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_detalle_doc"));

                    b.Property<string>("estatus_documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fecha_validacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_requisito")
                        .HasColumnType("int");

                    b.Property<int>("id_solicitud")
                        .HasColumnType("int");

                    b.Property<string>("motivo_rechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_archivo_fisico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_detalle_doc");

                    b.HasIndex("id_requisito");

                    b.HasIndex("id_solicitud");

                    b.ToTable("CE_TramitesDetalleDocumentos", "dbo");
                });

            modelBuilder.Entity("ControlEscolar.Models.DetalleSolicitudViewModel", b =>
                {
                    b.Property<string>("ArchivoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdTramite")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("DetalleSolicitudViewModel");
                });

            modelBuilder.Entity("ControlEscolar.Models.InfoAlumnoViewModel", b =>
                {
                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("InfoAlumnoViewModel");
                });

            modelBuilder.Entity("ControlEscolar.Models.InscripcionEntity", b =>
                {
                    b.Property<int>("academiccontrol_inscription_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_inscription_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_inscription_ID"));

                    b.Property<string>("academiccontrol_inscription_TSUEnrollment")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_inscription_TSUEnrollment");


                    b.Property<bool>("academiccontrol_inscription_actaValidada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("academiccontrol_inscription_actaValidada");

                    b.Property<string>("academiccontrol_inscription_birthCertificatePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_inscription_birthCertificatePath");


                    b.Property<bool>("academiccontrol_inscription_boletaValidada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("academiccontrol_inscription_boletaValidada");

                    b.Property<string>("academiccontrol_inscription_careerRequested")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_inscription_careerRequested");

                    b.Property<DateTime>("academiccontrol_inscription_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_createdDate")
                        .HasDefaultValueSql("GETDATE()");


                    b.Property<string>("academiccontrol_inscription_curpPdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_inscription_curpPdfPath");

                    b.Property<bool>("academiccontrol_inscription_curpValidado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("academiccontrol_inscription_curpValidado");

                    b.Property<string>("academiccontrol_inscription_enrollment")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_inscription_enrollment");


                    b.Property<bool>("academiccontrol_inscription_hasTSUEnrollment")
                        .HasColumnType("bit")
                        .HasColumnName("academiccontrol_inscription_hasTSUEnrollment");

                    b.Property<int>("academiccontrol_inscription_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_inscription_preinscriptionID");

                    b.Property<DateTime>("academiccontrol_inscription_registrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_registrationDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_inscription_rejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_inscription_rejectionReason");

                    b.Property<string>("academiccontrol_inscription_state")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("academiccontrol_inscription_state");

                    b.Property<bool>("academiccontrol_inscription_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_inscription_status");

                    b.Property<string>("academiccontrol_inscription_transcriptPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_inscription_transcriptPath");

                    b.HasKey("academiccontrol_inscription_ID");

                    b.HasIndex("academiccontrol_inscription_enrollment")
                        .IsUnique()
                        .HasFilter("[academiccontrol_inscription_enrollment] IS NOT NULL");

                    b.HasIndex("academiccontrol_inscription_preinscriptionID");

                    b.ToTable("academiccontrol_inscription_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.ManagementUser", b =>
                {
                    b.Property<int>("management_user_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("management_user_ID"));

                    b.Property<string>("management_user_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("management_user_IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("management_user_LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("management_user_LockReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_user_PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("management_user_PersonID")
                        .HasColumnType("int");

                    b.Property<int?>("management_user_RoleID")
                        .HasColumnType("int");

                    b.Property<string>("management_user_Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("management_user_createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("management_user_status")
                        .HasColumnType("bit");

                    b.HasKey("management_user_ID");

                    b.ToTable("management_user_table");
                });

            modelBuilder.Entity("ControlEscolar.Models.PeriodoInscripcionEntity", b =>
                {
                    b.Property<int>("academiccontrol_inscription_period_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_inscription_period_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_inscription_period_ID"));

                    b.Property<DateTime>("academiccontrol_inscription_period_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_period_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("academiccontrol_inscription_period_endDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_period_endDate");

                    b.Property<string>("academiccontrol_inscription_period_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_inscription_period_name");

                    b.Property<DateTime>("academiccontrol_inscription_period_startDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_inscription_period_startDate");

                    b.Property<bool>("academiccontrol_inscription_period_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_inscription_period_status");

                    b.HasKey("academiccontrol_inscription_period_ID");

                    b.ToTable("academiccontrol_inscription_period_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionDatosPersonalesEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_personaldata_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_personaldata_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_personaldata_ID"));

                    b.Property<string>("academiccontrol_preinscription_personaldata_CURP")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nchar(18)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_CURP")
                        .IsFixedLength();

                    b.Property<DateTime>("academiccontrol_preinscription_personaldata_birthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_personaldata_birthDate");

                    b.Property<DateTime>("academiccontrol_preinscription_personaldata_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_personaldata_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_personaldata_email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_email");

                    b.Property<string>("academiccontrol_preinscription_personaldata_gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_gender");

                    b.Property<string>("academiccontrol_preinscription_personaldata_maritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_maritalStatus");

                    b.Property<string>("academiccontrol_preinscription_personaldata_maternalSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_maternalSurname");

                    b.Property<string>("academiccontrol_preinscription_personaldata_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_name");

                    b.Property<string>("academiccontrol_preinscription_personaldata_paternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_paternalSurname");

                    b.Property<string>("academiccontrol_preinscription_personaldata_phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_preinscription_personaldata_phone");

                    b.Property<int>("academiccontrol_preinscription_personaldata_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_personaldata_preinscriptionID");

                    b.Property<bool>("academiccontrol_preinscription_personaldata_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_personaldata_status");

                    b.HasKey("academiccontrol_preinscription_personaldata_ID");

                    b.HasIndex("academiccontrol_preinscription_personaldata_preinscriptionID")
                        .IsUnique();

                    b.ToTable("academiccontrol_preinscription_personaldata_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionDomicilioEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_address_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_address_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_address_ID"));

                    b.Property<DateTime>("academiccontrol_preinscription_address_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_address_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_address_exteriorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("academiccontrol_preinscription_address_exteriorNumber");

                    b.Property<string>("academiccontrol_preinscription_address_municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_address_municipality");

                    b.Property<string>("academiccontrol_preinscription_address_neighborhood")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("academiccontrol_preinscription_address_neighborhood");

                    b.Property<int>("academiccontrol_preinscription_address_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_address_preinscriptionID");

                    b.Property<string>("academiccontrol_preinscription_address_state")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_address_state");

                    b.Property<bool>("academiccontrol_preinscription_address_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_address_status");

                    b.Property<string>("academiccontrol_preinscription_address_street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_preinscription_address_street");

                    b.Property<string>("academiccontrol_preinscription_address_zipCode")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .HasColumnName("academiccontrol_preinscription_address_zipCode")
                        .IsFixedLength();

                    b.HasKey("academiccontrol_preinscription_address_ID");

                    b.HasIndex("academiccontrol_preinscription_address_preinscriptionID")
                        .IsUnique();

                    b.ToTable("academiccontrol_preinscription_address_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_ID"));

                    b.Property<decimal>("academiccontrol_preinscription_average")
                        .HasColumnType("DECIMAL(4,2)")
                        .HasColumnName("academiccontrol_preinscription_average");

                    b.Property<string>("academiccontrol_preinscription_careerRequested")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_preinscription_careerRequested");

                    b.Property<DateTime>("academiccontrol_preinscription_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_diffusionMedia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("academiccontrol_preinscription_diffusionMedia");

                    b.Property<string>("academiccontrol_preinscription_folio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_preinscription_folio");

                    b.Property<DateTime>("academiccontrol_preinscription_registrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_registrationDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_rejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_preinscription_rejectionReason");

                    b.Property<string>("academiccontrol_preinscription_state")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("academiccontrol_preinscription_state");

                    b.Property<bool>("academiccontrol_preinscription_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_status");

                    b.HasKey("academiccontrol_preinscription_ID");

                    b.HasIndex("academiccontrol_preinscription_folio")
                        .IsUnique()
                        .HasFilter("[academiccontrol_preinscription_folio] IS NOT NULL");

                    b.ToTable("academiccontrol_preinscription_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionEscolarEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_academic_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_academic_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_academic_ID"));

                    b.Property<string>("academiccontrol_preinscription_academic_CCT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_preinscription_academic_CCT");

                    b.Property<DateTime>("academiccontrol_preinscription_academic_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_academic_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("academiccontrol_preinscription_academic_endDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_academic_endDate");

                    b.Property<string>("academiccontrol_preinscription_academic_originSchool")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_preinscription_academic_originSchool");

                    b.Property<int>("academiccontrol_preinscription_academic_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_academic_preinscriptionID");

                    b.Property<string>("academiccontrol_preinscription_academic_schoolMunicipality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_academic_schoolMunicipality");

                    b.Property<string>("academiccontrol_preinscription_academic_schoolState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_academic_schoolState");

                    b.Property<DateTime?>("academiccontrol_preinscription_academic_startDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_academic_startDate");

                    b.Property<bool>("academiccontrol_preinscription_academic_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_academic_status");

                    b.HasKey("academiccontrol_preinscription_academic_ID");

                    b.HasIndex("academiccontrol_preinscription_academic_preinscriptionID")
                        .IsUnique();

                    b.ToTable("academiccontrol_preinscription_academic_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionSaludEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_health_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_health_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_health_ID"));

                    b.Property<string>("academiccontrol_preinscription_health_comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("academiccontrol_preinscription_health_comments");

                    b.Property<DateTime>("academiccontrol_preinscription_health_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_health_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_health_disabilityDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("academiccontrol_preinscription_health_disabilityDescription");

                    b.Property<bool>("academiccontrol_preinscription_health_hasChildren")
                        .HasColumnType("bit")
                        .HasColumnName("academiccontrol_preinscription_health_hasChildren");

                    b.Property<bool>("academiccontrol_preinscription_health_hasDisability")
                        .HasColumnType("bit")
                        .HasColumnName("academiccontrol_preinscription_health_hasDisability");

                    b.Property<bool>("academiccontrol_preinscription_health_indigenousCommunity")
                        .HasColumnType("bit")
                        .HasColumnName("academiccontrol_preinscription_health_indigenousCommunity");

                    b.Property<string>("academiccontrol_preinscription_health_indigenousCommunityDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("academiccontrol_preinscription_health_indigenousCommunityDescription");

                    b.Property<string>("academiccontrol_preinscription_health_medicalService")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academiccontrol_preinscription_health_medicalService");

                    b.Property<int>("academiccontrol_preinscription_health_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_health_preinscriptionID");

                    b.Property<bool>("academiccontrol_preinscription_health_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_health_status");

                    b.HasKey("academiccontrol_preinscription_health_ID");

                    b.HasIndex("academiccontrol_preinscription_health_preinscriptionID")
                        .IsUnique();

                    b.ToTable("academiccontrol_preinscription_health_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionTutorEntity", b =>
                {
                    b.Property<int>("academiccontrol_preinscription_tutor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_tutor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academiccontrol_preinscription_tutor_ID"));

                    b.Property<DateTime>("academiccontrol_preinscription_tutor_createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("academiccontrol_preinscription_tutor_createdDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("academiccontrol_preinscription_tutor_fullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academiccontrol_preinscription_tutor_fullName");

                    b.Property<string>("academiccontrol_preinscription_tutor_phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("academiccontrol_preinscription_tutor_phone");

                    b.Property<int>("academiccontrol_preinscription_tutor_preinscriptionID")
                        .HasColumnType("int")
                        .HasColumnName("academiccontrol_preinscription_tutor_preinscriptionID");

                    b.Property<string>("academiccontrol_preinscription_tutor_relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("academiccontrol_preinscription_tutor_relationship");

                    b.Property<bool>("academiccontrol_preinscription_tutor_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("academiccontrol_preinscription_tutor_status");

                    b.HasKey("academiccontrol_preinscription_tutor_ID");

                    b.HasIndex("academiccontrol_preinscription_tutor_preinscriptionID")
                        .IsUnique();

                    b.ToTable("academiccontrol_preinscription_tutor_table", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.RequisitoRevisionViewModel", b =>
                {
                    b.Property<bool>("ArchivoExiste")
                        .HasColumnType("bit");

                    b.Property<bool>("EsFotografia")
                        .HasColumnType("bit");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRequisito")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivoFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRequisito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RequisitoRevisionViewModel");
                });

            modelBuilder.Entity("ControlEscolar.Models.RequisitoSolicitudViewModel", b =>
                {
                    b.Property<int>("IdRequisito")
                        .HasColumnType("int");

                    b.Property<string>("NombreRequisito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RequisitoSolicitudViewModel");
                });

            modelBuilder.Entity("ControlEscolar.Models.Requisito_Tramite", b =>
                {
                    b.Property<int>("id_requisito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_requisito"));

                    b.Property<int>("id_tramite")
                        .HasColumnType("int");

                    b.Property<string>("nombre_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_requisito");

                    b.HasIndex("id_tramite");

                    b.ToTable("CE_TramitesRequisitos", "dbo");
                });

            modelBuilder.Entity("ControlEscolar.Models.Solicitud", b =>
                {
                    b.Property<int>("tramites_solicitud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tramites_solicitud_id"));

                    b.Property<int>("id_tramite")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_propietario")
                        .HasColumnType("int");

                    b.Property<string>("tramites_solicitud_archivo_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tramites_solicitud_estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tramites_solicitud_fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("tramites_solicitud_observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tramites_solicitud_id");

                    b.HasIndex("id_tramite");

                    b.ToTable("CE_TramitesSolicitud", "dbo");
                });

            modelBuilder.Entity("ControlEscolar.Models.TramiteResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.ToTable("TramiteResult");
                });

            modelBuilder.Entity("ControlEscolar.Models.VisitaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("EnfermedadesCronicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecificarAlergia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FrecuenciaCardiaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrecuenciaRespiratoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("PresionArterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saturacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Talla")
                        .HasColumnType("float");

                    b.Property<double?>("Temperatura")
                        .HasColumnType("float");

                    b.Property<bool>("TieneAlergias")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Visitas", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.VisitaPsicologica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicacionPsiquiatrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoConsultaPrevia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TerapiaPrevia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VisitasPsicologicas", (string)null);
                });

            modelBuilder.Entity("ControlEscolar.Models.DetalleDocumentos", b =>
                {
                    b.HasOne("ControlEscolar.Models.Requisito_Tramite", "Requisito")
                        .WithMany()
                        .HasForeignKey("id_requisito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEscolar.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("id_solicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisito");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("ControlEscolar.Models.InscripcionEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithMany()
                        .HasForeignKey("academiccontrol_inscription_preinscriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionDatosPersonalesEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithOne("DatosPersonales")
                        .HasForeignKey("ControlEscolar.Models.PreinscripcionDatosPersonalesEntity", "academiccontrol_preinscription_personaldata_preinscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionDomicilioEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithOne("Domicilio")
                        .HasForeignKey("ControlEscolar.Models.PreinscripcionDomicilioEntity", "academiccontrol_preinscription_address_preinscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionEscolarEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithOne("DatosEscolares")
                        .HasForeignKey("ControlEscolar.Models.PreinscripcionEscolarEntity", "academiccontrol_preinscription_academic_preinscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionSaludEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithOne("Salud")
                        .HasForeignKey("ControlEscolar.Models.PreinscripcionSaludEntity", "academiccontrol_preinscription_health_preinscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionTutorEntity", b =>
                {
                    b.HasOne("ControlEscolar.Models.PreinscripcionEntity", "Preinscripcion")
                        .WithOne("Tutor")
                        .HasForeignKey("ControlEscolar.Models.PreinscripcionTutorEntity", "academiccontrol_preinscription_tutor_preinscriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("ControlEscolar.Models.Requisito_Tramite", b =>
                {
                    b.HasOne("ControlEscolar.Models.Cat_Tramites", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_tramite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControlEscolar.Models.Solicitud", b =>
                {
                    b.HasOne("ControlEscolar.Models.Cat_Tramites", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_tramite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControlEscolar.Models.PreinscripcionEntity", b =>
                {
                    b.Navigation("DatosEscolares");

                    b.Navigation("DatosPersonales");

                    b.Navigation("Domicilio");

                    b.Navigation("Salud");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
